### ISSUE TITLE
Config.yml resets itself every time the server starts

### ISSUE THREAD

**Issue by JuicePMMP** [koningcool/LoadAllWorlds#11] opened 2020-11-29 23:48 UTC
I deleted the plugin and the plugin data then restarted my server. I downloaded the newest version directly off of poggit 1.1.1 (27 Sep 2020) and the "Fix for overwriting of config.yml at server restart" is not fixed for me. I saw a new looking config and set on startup load to true then restarted my server. After that the config was reverted to the same look as the older plugin version and all data was wiped to default.

**Comment by koningcool** [comment] 2020-11-30 16:42
Hello JuicePMMP. Thank you for your message about my plugin. I myself have just done a test with an overwrite problem. In my test everything went well. If all goes well in version 1.1.1 the config.yml should no longer overwrite itself. And also don't go back to the old look of the config.yml. If I understand correctly, that will happen to you. Do you want to try removing the plugin_data folder and then restart your server. Doesn't this work? Then you can try to completely remove the plugin from your server. And then completely reinstall the plugin. Should this not work either. Then you can send a message in this issue. Thanks in advance.

**Comment by JuicePMMP** [comment] 2020-11-30 19:45
What happens is I delete the plugin data (I already have the new plugin version), and then I restart the server. I open config and it shows the new one and I change on startup to true, then I save and restart the server to load all my worlds. After server has been restarted, if I open the config then on startup is now false and the entire config looks like the old version (I did not change it to look like it, it just happens after restart). 

Here is what happens when I to try and solve this problem.

1- I deleted the plugin and plugin data

2- I downloaded a new copy of the newest version on poggit and uploaded to my server then restarted the server

3- Went into config after restart and it shows newer config format and I set on startup to true (only change) then save it

4- I restart my server and join, once on I check with multiworld and see all but 4 worlds are unloaded

5- After seeing it is not loaded I check config and it is now back to the pre 1.1.1 config format and on startup is now set to false

I do not think this would be because I am using a world manager like Multiworld since this plugin has worked for me in the past to load all worlds when I used various world management and editing plugins.

**Comment by JuicePMMP** [comment] 2020-11-30 20:02
I downloaded it off of github directly [1.1.1 Release](https://github.com/koningcool/LoadAllWorlds/releases/tag/1.1.1) in case for some odd reason that would work and poggit was the problem, however I get the same issue.

**Comment by koningcool** [comment] 2020-12-01 17:12
Thanks again for your message. Can you send a full list of the plugins and the corresponding plugin version so that I can act out the problem. If the config.yml is also reset with me, I can give the plugin a bugfix update.

**Comment by JuicePMMP** [comment] 2020-12-01 20:26
Every single plugin or just the other ones dealing with world management?

I currently am only using 1 world manager, 

MultiWorld  version 1.5.2  API 3.0.0

**Comment by koningcool** [comment] 2020-12-02 15:28
Hi, I would like to know all plugins + their versions just to be sure.
This way I can reproduce the problem as closely as possible.

**Comment by JuicePMMP** [comment] 2020-12-02 23:14
Long list, some of them are custom made so you may not find them all on poggit

AlwaysSpawn v2.2.4, 
AutoClearLagg v3.1.0, 
AutoInv v0.0.10, 
AutoXP v1.1.0, 
BlazinBroadcasts v1.0.3, 
Colormatic v1.0.3-1, 
CommandFix v1.0.0, 
CoolTrading v1.0.4, 
Crates v1.0.0, 
CustomBooks v1.0.0, 
CustomTell v1.0.0, 
DiscordLogger v1, 
DynamicRepairs v0.1.0, 
EconomyAPI v5.7.2, 
FlyPE v2.0.3, 
FoodEffects v1.2.0, 
FormAPI v1.3.0, 
LoadAllWorlds v1.1.1, 
LuckyBlock v0.0.3, 
MineReset v3.2.0, 
MineRewards v1.0.0, 
MultiWorld v1.5.2, 
MyPlot v1.9.0-pre, 
NaviCompass v2.3.3, 
NoFallDamage v1.0, 
Pen v1.0.2, 
PiggyCustomEnchants v2.3.0, 
PiggyCustomEnchantsShop v1.3.5, 
PiggyShopUI v2.1.1, 
PlayerInfo v2.1.4, 
Powertools v1.0.0, 
Prison v1.0.0, 
Protection v1.0.0, 
RanksAndPermissions v1.0.0, 
RenameItems v2.0, 
Rewards v4.0, 
ScoreHud v5.2.0, 
SellAll v1.3.0, 
SignServerStats v1.1.1, 
SimpleHome v1.0.3, 
SimpleWarp v4.0.1, 
Slapper v1.6.1, 
Snow v1.0.1, 
SpinningCoin v1.0, 
Texter v3.4.10, 
VanillaCoordinates v1.0.0, 
Duels v1.1.0

**Comment by koningcool** [comment] 2021-01-16 08:01
My very big apologies for my very late reply. Could you attach the phars of your plugins? This way I don't have to install every plugin one by one, and this way I can also test plugins that are not on poggit with my plugin. It might also be useful if you send the plugin_data of your plugins (also as an attachment) so that I can recreate the situation even better. Again apologies for the very late reply. Thank you in advance!

**Comment by koningcool** [comment] 2021-01-18 11:06
I also did an update I don't think this solves the problem for you but you can try.

**Comment by koningcool** [comment] 2021-01-29 15:34
With this comment I close the issue because I cannot reproduce the problem well enough.

**Closed** 2022-04-10 18:19 UTC
Labels: bug, important, Is being worked on
